#!/bin/sh

commit_message=$(cat "$1")

case "$commit_message" in
  Merge\ *|Revert\ *|Pull\ *|fixup\!*|squash\!*)
    exit 0
    ;;
esac

conventional_regex='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9_-]+\))?: .{1,}$'

if ! echo "$commit_message" | grep -Eq "$conventional_regex"; then
    echo "Invalid commit message, please use Conventional Commits."
    echo "Correct format: type(scope) -> description"
    exit 1
fi

exit 0