name: Playwright Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 25 # Ajustado a tu versión
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'maven'

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Build Frontend
      run: |
        npm ci
        npm run build

    - name: Setup Backend Environment
      run: |
        git clone https://github.com/ispp-knot/dondesiempre-backend.git backend
        cd backend
        cp .env.example .env
        docker compose up -d # Levanta la BD
        chmod +x mvnw        # Importante: permisos para Linux

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
      env:
        # Pasa aquí variables de entorno si tus tests las necesitan
        NODE_ENV: test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30